/*
 * generated by Xtext 2.23.0
 */
package at.jku.mosumo.lang.ide;

import at.jku.mosumo.lang.MosumoRuntimeModule;
import at.jku.mosumo.lang.MosumoStandaloneSetup;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class MosumoIdeSetup extends MosumoStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new MosumoRuntimeModule(), new MosumoIdeModule()));
	}
	
}
