/*
 * generated by Xtext 2.23.0
 */
package at.jku.mosumo.lang.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class MosumoUiModule extends AbstractMosumoUiModule {

	public MosumoUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
