/*
 * generated by Xtext 2.23.0
 */
package at.jku.mosumo.lang;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class MosumoStandaloneSetup extends MosumoStandaloneSetupGenerated {

	public static void doSetup() {
		new MosumoStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
