/*
 * generated by Xtext 2.23.0
 */
package at.jku.mosumo.lang;

import org.eclipse.xtext.naming.IQualifiedNameProvider;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MosumoRuntimeModule extends AbstractMosumoRuntimeModule {
	
	@Override
	public Class<? extends IQualifiedNameProvider> bindIQualifiedNameProvider() {
		return MosumoQualifiedNameProvider.class;
	}
}
