/*
 * generated by Xtext 2.23.0
 */
package at.jku.mosumo.lang.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class MosumoAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("at/jku/mosumo/lang/parser/antlr/internal/InternalMosumo.tokens");
	}
}
