/*
 * generated by Xtext 2.23.0
 */
package at.jku.mosumo.lang.parser.antlr;

import at.jku.mosumo.lang.parser.antlr.internal.InternalMosumoParser;
import at.jku.mosumo.lang.services.MosumoGrammarAccess;
import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class MosumoParser extends AbstractAntlrParser {

	@Inject
	private MosumoGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalMosumoParser createParser(XtextTokenStream stream) {
		return new InternalMosumoParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "MOConfig";
	}

	public MosumoGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MosumoGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
