/*
 * generated by Xtext 2.23.0
 */
package at.jku.mosumo.lang.ide.contentassist.antlr;

import at.jku.mosumo.lang.ide.contentassist.antlr.internal.InternalMosumoParser;
import at.jku.mosumo.lang.services.MosumoGrammarAccess;
import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class MosumoParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(MosumoGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, MosumoGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getEClassifierAccess().getAlternatives(), "rule__EClassifier__Alternatives");
			builder.put(grammarAccess.getEStructuralFeatureAccess().getAlternatives(), "rule__EStructuralFeature__Alternatives");
			builder.put(grammarAccess.getMOElementAccess().getAlternatives(), "rule__MOElement__Alternatives");
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getEBooleanAccess().getAlternatives(), "rule__EBoolean__Alternatives");
			builder.put(grammarAccess.getMOConfigAccess().getGroup(), "rule__MOConfig__Group__0");
			builder.put(grammarAccess.getMOConfigAccess().getGroup_3(), "rule__MOConfig__Group_3__0");
			builder.put(grammarAccess.getMOConfigAccess().getGroup_4(), "rule__MOConfig__Group_4__0");
			builder.put(grammarAccess.getMOConfigAccess().getGroup_9(), "rule__MOConfig__Group_9__0");
			builder.put(grammarAccess.getMOConfigAccess().getGroup_9_3(), "rule__MOConfig__Group_9_3__0");
			builder.put(grammarAccess.getServerAccess().getGroup(), "rule__Server__Group__0");
			builder.put(grammarAccess.getServerAccess().getGroup_4(), "rule__Server__Group_4__0");
			builder.put(grammarAccess.getServerAccess().getGroup_5(), "rule__Server__Group_5__0");
			builder.put(grammarAccess.getEPackageAccess().getGroup(), "rule__EPackage__Group__0");
			builder.put(grammarAccess.getEPackageAccess().getGroup_4(), "rule__EPackage__Group_4__0");
			builder.put(grammarAccess.getEPackageAccess().getGroup_5(), "rule__EPackage__Group_5__0");
			builder.put(grammarAccess.getEPackageAccess().getGroup_6(), "rule__EPackage__Group_6__0");
			builder.put(grammarAccess.getEPackageAccess().getGroup_6_3(), "rule__EPackage__Group_6_3__0");
			builder.put(grammarAccess.getEPackageAccess().getGroup_7(), "rule__EPackage__Group_7__0");
			builder.put(grammarAccess.getEPackageAccess().getGroup_7_3(), "rule__EPackage__Group_7_3__0");
			builder.put(grammarAccess.getEPackageAccess().getGroup_8(), "rule__EPackage__Group_8__0");
			builder.put(grammarAccess.getEPackageAccess().getGroup_8_3(), "rule__EPackage__Group_8_3__0");
			builder.put(grammarAccess.getMoSystemAccess().getGroup(), "rule__MoSystem__Group__0");
			builder.put(grammarAccess.getMoSystemAccess().getGroup_3(), "rule__MoSystem__Group_3__0");
			builder.put(grammarAccess.getMoSystemAccess().getGroup_4(), "rule__MoSystem__Group_4__0");
			builder.put(grammarAccess.getMoSystemAccess().getGroup_4_3(), "rule__MoSystem__Group_4_3__0");
			builder.put(grammarAccess.getConnectionOptionsAccess().getGroup(), "rule__ConnectionOptions__Group__0");
			builder.put(grammarAccess.getConnectionOptionsAccess().getGroup_3(), "rule__ConnectionOptions__Group_3__0");
			builder.put(grammarAccess.getConnectionOptionsAccess().getGroup_4(), "rule__ConnectionOptions__Group_4__0");
			builder.put(grammarAccess.getConnectionOptionsAccess().getGroup_5(), "rule__ConnectionOptions__Group_5__0");
			builder.put(grammarAccess.getConnectionOptionsAccess().getGroup_6(), "rule__ConnectionOptions__Group_6__0");
			builder.put(grammarAccess.getEIntegerObjectAccess().getGroup(), "rule__EIntegerObject__Group__0");
			builder.put(grammarAccess.getEAnnotationAccess().getGroup(), "rule__EAnnotation__Group__0");
			builder.put(grammarAccess.getEAnnotationAccess().getGroup_3(), "rule__EAnnotation__Group_3__0");
			builder.put(grammarAccess.getEAnnotationAccess().getGroup_4(), "rule__EAnnotation__Group_4__0");
			builder.put(grammarAccess.getEAnnotationAccess().getGroup_4_3(), "rule__EAnnotation__Group_4_3__0");
			builder.put(grammarAccess.getEAnnotationAccess().getGroup_5(), "rule__EAnnotation__Group_5__0");
			builder.put(grammarAccess.getEAnnotationAccess().getGroup_5_3(), "rule__EAnnotation__Group_5_3__0");
			builder.put(grammarAccess.getEAnnotationAccess().getGroup_6(), "rule__EAnnotation__Group_6__0");
			builder.put(grammarAccess.getEAnnotationAccess().getGroup_6_3(), "rule__EAnnotation__Group_6_3__0");
			builder.put(grammarAccess.getEAnnotationAccess().getGroup_7(), "rule__EAnnotation__Group_7__0");
			builder.put(grammarAccess.getEAnnotationAccess().getGroup_7_3(), "rule__EAnnotation__Group_7_3__0");
			builder.put(grammarAccess.getEStringToStringMapEntryAccess().getGroup(), "rule__EStringToStringMapEntry__Group__0");
			builder.put(grammarAccess.getEStringToStringMapEntryAccess().getGroup_3(), "rule__EStringToStringMapEntry__Group_3__0");
			builder.put(grammarAccess.getEStringToStringMapEntryAccess().getGroup_4(), "rule__EStringToStringMapEntry__Group_4__0");
			builder.put(grammarAccess.getEObjectAccess().getGroup(), "rule__EObject__Group__0");
			builder.put(grammarAccess.getETypeParameterAccess().getGroup(), "rule__ETypeParameter__Group__0");
			builder.put(grammarAccess.getETypeParameterAccess().getGroup_4(), "rule__ETypeParameter__Group_4__0");
			builder.put(grammarAccess.getETypeParameterAccess().getGroup_4_3(), "rule__ETypeParameter__Group_4_3__0");
			builder.put(grammarAccess.getETypeParameterAccess().getGroup_5(), "rule__ETypeParameter__Group_5__0");
			builder.put(grammarAccess.getETypeParameterAccess().getGroup_5_3(), "rule__ETypeParameter__Group_5_3__0");
			builder.put(grammarAccess.getEClassAccess().getGroup(), "rule__EClass__Group__0");
			builder.put(grammarAccess.getEClassAccess().getGroup_6(), "rule__EClass__Group_6__0");
			builder.put(grammarAccess.getEClassAccess().getGroup_7(), "rule__EClass__Group_7__0");
			builder.put(grammarAccess.getEClassAccess().getGroup_8(), "rule__EClass__Group_8__0");
			builder.put(grammarAccess.getEClassAccess().getGroup_8_3(), "rule__EClass__Group_8_3__0");
			builder.put(grammarAccess.getEClassAccess().getGroup_9(), "rule__EClass__Group_9__0");
			builder.put(grammarAccess.getEClassAccess().getGroup_9_3(), "rule__EClass__Group_9_3__0");
			builder.put(grammarAccess.getEClassAccess().getGroup_10(), "rule__EClass__Group_10__0");
			builder.put(grammarAccess.getEClassAccess().getGroup_10_3(), "rule__EClass__Group_10_3__0");
			builder.put(grammarAccess.getEClassAccess().getGroup_11(), "rule__EClass__Group_11__0");
			builder.put(grammarAccess.getEClassAccess().getGroup_11_3(), "rule__EClass__Group_11_3__0");
			builder.put(grammarAccess.getEClassAccess().getGroup_12(), "rule__EClass__Group_12__0");
			builder.put(grammarAccess.getEClassAccess().getGroup_12_3(), "rule__EClass__Group_12_3__0");
			builder.put(grammarAccess.getEClassAccess().getGroup_13(), "rule__EClass__Group_13__0");
			builder.put(grammarAccess.getEClassAccess().getGroup_13_3(), "rule__EClass__Group_13_3__0");
			builder.put(grammarAccess.getEDataType_ImplAccess().getGroup(), "rule__EDataType_Impl__Group__0");
			builder.put(grammarAccess.getEDataType_ImplAccess().getGroup_4(), "rule__EDataType_Impl__Group_4__0");
			builder.put(grammarAccess.getEDataType_ImplAccess().getGroup_5(), "rule__EDataType_Impl__Group_5__0");
			builder.put(grammarAccess.getEDataType_ImplAccess().getGroup_6(), "rule__EDataType_Impl__Group_6__0");
			builder.put(grammarAccess.getEDataType_ImplAccess().getGroup_7(), "rule__EDataType_Impl__Group_7__0");
			builder.put(grammarAccess.getEDataType_ImplAccess().getGroup_7_3(), "rule__EDataType_Impl__Group_7_3__0");
			builder.put(grammarAccess.getEDataType_ImplAccess().getGroup_8(), "rule__EDataType_Impl__Group_8__0");
			builder.put(grammarAccess.getEDataType_ImplAccess().getGroup_8_3(), "rule__EDataType_Impl__Group_8_3__0");
			builder.put(grammarAccess.getEEnumAccess().getGroup(), "rule__EEnum__Group__0");
			builder.put(grammarAccess.getEEnumAccess().getGroup_4(), "rule__EEnum__Group_4__0");
			builder.put(grammarAccess.getEEnumAccess().getGroup_5(), "rule__EEnum__Group_5__0");
			builder.put(grammarAccess.getEEnumAccess().getGroup_6(), "rule__EEnum__Group_6__0");
			builder.put(grammarAccess.getEEnumAccess().getGroup_7(), "rule__EEnum__Group_7__0");
			builder.put(grammarAccess.getEEnumAccess().getGroup_7_3(), "rule__EEnum__Group_7_3__0");
			builder.put(grammarAccess.getEEnumAccess().getGroup_8(), "rule__EEnum__Group_8__0");
			builder.put(grammarAccess.getEEnumAccess().getGroup_8_3(), "rule__EEnum__Group_8_3__0");
			builder.put(grammarAccess.getEEnumAccess().getGroup_9(), "rule__EEnum__Group_9__0");
			builder.put(grammarAccess.getEEnumAccess().getGroup_9_3(), "rule__EEnum__Group_9_3__0");
			builder.put(grammarAccess.getEGenericTypeAccess().getGroup(), "rule__EGenericType__Group__0");
			builder.put(grammarAccess.getEGenericTypeAccess().getGroup_3(), "rule__EGenericType__Group_3__0");
			builder.put(grammarAccess.getEGenericTypeAccess().getGroup_4(), "rule__EGenericType__Group_4__0");
			builder.put(grammarAccess.getEGenericTypeAccess().getGroup_5(), "rule__EGenericType__Group_5__0");
			builder.put(grammarAccess.getEGenericTypeAccess().getGroup_6(), "rule__EGenericType__Group_6__0");
			builder.put(grammarAccess.getEGenericTypeAccess().getGroup_6_3(), "rule__EGenericType__Group_6_3__0");
			builder.put(grammarAccess.getEGenericTypeAccess().getGroup_7(), "rule__EGenericType__Group_7__0");
			builder.put(grammarAccess.getEOperationAccess().getGroup(), "rule__EOperation__Group__0");
			builder.put(grammarAccess.getEOperationAccess().getGroup_4(), "rule__EOperation__Group_4__0");
			builder.put(grammarAccess.getEOperationAccess().getGroup_5(), "rule__EOperation__Group_5__0");
			builder.put(grammarAccess.getEOperationAccess().getGroup_6(), "rule__EOperation__Group_6__0");
			builder.put(grammarAccess.getEOperationAccess().getGroup_7(), "rule__EOperation__Group_7__0");
			builder.put(grammarAccess.getEOperationAccess().getGroup_8(), "rule__EOperation__Group_8__0");
			builder.put(grammarAccess.getEOperationAccess().getGroup_9(), "rule__EOperation__Group_9__0");
			builder.put(grammarAccess.getEOperationAccess().getGroup_9_3(), "rule__EOperation__Group_9_3__0");
			builder.put(grammarAccess.getEOperationAccess().getGroup_10(), "rule__EOperation__Group_10__0");
			builder.put(grammarAccess.getEOperationAccess().getGroup_10_3(), "rule__EOperation__Group_10_3__0");
			builder.put(grammarAccess.getEOperationAccess().getGroup_11(), "rule__EOperation__Group_11__0");
			builder.put(grammarAccess.getEOperationAccess().getGroup_12(), "rule__EOperation__Group_12__0");
			builder.put(grammarAccess.getEOperationAccess().getGroup_12_3(), "rule__EOperation__Group_12_3__0");
			builder.put(grammarAccess.getEOperationAccess().getGroup_13(), "rule__EOperation__Group_13__0");
			builder.put(grammarAccess.getEOperationAccess().getGroup_13_3(), "rule__EOperation__Group_13_3__0");
			builder.put(grammarAccess.getEOperationAccess().getGroup_14(), "rule__EOperation__Group_14__0");
			builder.put(grammarAccess.getEOperationAccess().getGroup_14_3(), "rule__EOperation__Group_14_3__0");
			builder.put(grammarAccess.getEIntAccess().getGroup(), "rule__EInt__Group__0");
			builder.put(grammarAccess.getEParameterAccess().getGroup(), "rule__EParameter__Group__0");
			builder.put(grammarAccess.getEParameterAccess().getGroup_4(), "rule__EParameter__Group_4__0");
			builder.put(grammarAccess.getEParameterAccess().getGroup_5(), "rule__EParameter__Group_5__0");
			builder.put(grammarAccess.getEParameterAccess().getGroup_6(), "rule__EParameter__Group_6__0");
			builder.put(grammarAccess.getEParameterAccess().getGroup_7(), "rule__EParameter__Group_7__0");
			builder.put(grammarAccess.getEParameterAccess().getGroup_8(), "rule__EParameter__Group_8__0");
			builder.put(grammarAccess.getEParameterAccess().getGroup_9(), "rule__EParameter__Group_9__0");
			builder.put(grammarAccess.getEParameterAccess().getGroup_9_3(), "rule__EParameter__Group_9_3__0");
			builder.put(grammarAccess.getEParameterAccess().getGroup_10(), "rule__EParameter__Group_10__0");
			builder.put(grammarAccess.getEAttributeAccess().getGroup(), "rule__EAttribute__Group__0");
			builder.put(grammarAccess.getEAttributeAccess().getGroup_9(), "rule__EAttribute__Group_9__0");
			builder.put(grammarAccess.getEAttributeAccess().getGroup_10(), "rule__EAttribute__Group_10__0");
			builder.put(grammarAccess.getEAttributeAccess().getGroup_11(), "rule__EAttribute__Group_11__0");
			builder.put(grammarAccess.getEAttributeAccess().getGroup_12(), "rule__EAttribute__Group_12__0");
			builder.put(grammarAccess.getEAttributeAccess().getGroup_13(), "rule__EAttribute__Group_13__0");
			builder.put(grammarAccess.getEAttributeAccess().getGroup_14(), "rule__EAttribute__Group_14__0");
			builder.put(grammarAccess.getEAttributeAccess().getGroup_15(), "rule__EAttribute__Group_15__0");
			builder.put(grammarAccess.getEAttributeAccess().getGroup_16(), "rule__EAttribute__Group_16__0");
			builder.put(grammarAccess.getEAttributeAccess().getGroup_16_3(), "rule__EAttribute__Group_16_3__0");
			builder.put(grammarAccess.getEAttributeAccess().getGroup_17(), "rule__EAttribute__Group_17__0");
			builder.put(grammarAccess.getEReferenceAccess().getGroup(), "rule__EReference__Group__0");
			builder.put(grammarAccess.getEReferenceAccess().getGroup_9(), "rule__EReference__Group_9__0");
			builder.put(grammarAccess.getEReferenceAccess().getGroup_10(), "rule__EReference__Group_10__0");
			builder.put(grammarAccess.getEReferenceAccess().getGroup_11(), "rule__EReference__Group_11__0");
			builder.put(grammarAccess.getEReferenceAccess().getGroup_12(), "rule__EReference__Group_12__0");
			builder.put(grammarAccess.getEReferenceAccess().getGroup_13(), "rule__EReference__Group_13__0");
			builder.put(grammarAccess.getEReferenceAccess().getGroup_14(), "rule__EReference__Group_14__0");
			builder.put(grammarAccess.getEReferenceAccess().getGroup_15(), "rule__EReference__Group_15__0");
			builder.put(grammarAccess.getEReferenceAccess().getGroup_16(), "rule__EReference__Group_16__0");
			builder.put(grammarAccess.getEReferenceAccess().getGroup_17(), "rule__EReference__Group_17__0");
			builder.put(grammarAccess.getEReferenceAccess().getGroup_18(), "rule__EReference__Group_18__0");
			builder.put(grammarAccess.getEReferenceAccess().getGroup_18_3(), "rule__EReference__Group_18_3__0");
			builder.put(grammarAccess.getEReferenceAccess().getGroup_19(), "rule__EReference__Group_19__0");
			builder.put(grammarAccess.getEReferenceAccess().getGroup_19_3(), "rule__EReference__Group_19_3__0");
			builder.put(grammarAccess.getEReferenceAccess().getGroup_20(), "rule__EReference__Group_20__0");
			builder.put(grammarAccess.getEEnumLiteralAccess().getGroup(), "rule__EEnumLiteral__Group__0");
			builder.put(grammarAccess.getEEnumLiteralAccess().getGroup_4(), "rule__EEnumLiteral__Group_4__0");
			builder.put(grammarAccess.getEEnumLiteralAccess().getGroup_5(), "rule__EEnumLiteral__Group_5__0");
			builder.put(grammarAccess.getEEnumLiteralAccess().getGroup_6(), "rule__EEnumLiteral__Group_6__0");
			builder.put(grammarAccess.getEEnumLiteralAccess().getGroup_6_3(), "rule__EEnumLiteral__Group_6_3__0");
			builder.put(grammarAccess.getMOAgentAccess().getGroup(), "rule__MOAgent__Group__0");
			builder.put(grammarAccess.getMOAgentAccess().getGroup_4(), "rule__MOAgent__Group_4__0");
			builder.put(grammarAccess.getMOAgentAccess().getGroup_5(), "rule__MOAgent__Group_5__0");
			builder.put(grammarAccess.getMOAgentAccess().getGroup_6(), "rule__MOAgent__Group_6__0");
			builder.put(grammarAccess.getMOAgentAccess().getGroup_7(), "rule__MOAgent__Group_7__0");
			builder.put(grammarAccess.getMOAgentAccess().getGroup_8(), "rule__MOAgent__Group_8__0");
			builder.put(grammarAccess.getMOAgentAccess().getGroup_8_3(), "rule__MOAgent__Group_8_3__0");
			builder.put(grammarAccess.getMOAgentAccess().getGroup_9(), "rule__MOAgent__Group_9__0");
			builder.put(grammarAccess.getMOAgentAccess().getGroup_9_3(), "rule__MOAgent__Group_9_3__0");
			builder.put(grammarAccess.getDerivedPropertyAccess().getGroup(), "rule__DerivedProperty__Group__0");
			builder.put(grammarAccess.getDerivedPropertyAccess().getGroup_4(), "rule__DerivedProperty__Group_4__0");
			builder.put(grammarAccess.getDerivedPropertyAccess().getGroup_5(), "rule__DerivedProperty__Group_5__0");
			builder.put(grammarAccess.getDerivedPropertyAccess().getGroup_6(), "rule__DerivedProperty__Group_6__0");
			builder.put(grammarAccess.getMOPropertyAccess().getGroup(), "rule__MOProperty__Group__0");
			builder.put(grammarAccess.getMOPropertyAccess().getGroup_4(), "rule__MOProperty__Group_4__0");
			builder.put(grammarAccess.getMOPropertyAccess().getGroup_5(), "rule__MOProperty__Group_5__0");
			builder.put(grammarAccess.getMOPropertyAccess().getGroup_6(), "rule__MOProperty__Group_6__0");
			builder.put(grammarAccess.getMOPropertyAccess().getGroup_7(), "rule__MOProperty__Group_7__0");
			builder.put(grammarAccess.getMOPropertyAccess().getGroup_7_3(), "rule__MOProperty__Group_7_3__0");
			builder.put(grammarAccess.getMOValueAccess().getGroup(), "rule__MOValue__Group__0");
			builder.put(grammarAccess.getMOValueAccess().getGroup_4(), "rule__MOValue__Group_4__0");
			builder.put(grammarAccess.getMOValueAccess().getGroup_5(), "rule__MOValue__Group_5__0");
			builder.put(grammarAccess.getMOValueAccess().getGroup_6(), "rule__MOValue__Group_6__0");
			builder.put(grammarAccess.getMOValueAccess().getGroup_7(), "rule__MOValue__Group_7__0");
			builder.put(grammarAccess.getMOValueAccess().getGroup_7_3(), "rule__MOValue__Group_7_3__0");
			builder.put(grammarAccess.getMOConfigAccess().getNameAssignment_1(), "rule__MOConfig__NameAssignment_1");
			builder.put(grammarAccess.getMOConfigAccess().getNamespaceAssignment_3_1(), "rule__MOConfig__NamespaceAssignment_3_1");
			builder.put(grammarAccess.getMOConfigAccess().getProjectNameAssignment_4_1(), "rule__MOConfig__ProjectNameAssignment_4_1");
			builder.put(grammarAccess.getMOConfigAccess().getDefaultServerAssignment_6(), "rule__MOConfig__DefaultServerAssignment_6");
			builder.put(grammarAccess.getMOConfigAccess().getEPackageAssignment_8(), "rule__MOConfig__EPackageAssignment_8");
			builder.put(grammarAccess.getMOConfigAccess().getServersAssignment_9_2(), "rule__MOConfig__ServersAssignment_9_2");
			builder.put(grammarAccess.getMOConfigAccess().getServersAssignment_9_3_1(), "rule__MOConfig__ServersAssignment_9_3_1");
			builder.put(grammarAccess.getMOConfigAccess().getSystemAssignment_11(), "rule__MOConfig__SystemAssignment_11");
			builder.put(grammarAccess.getServerAccess().getNameAssignment_2(), "rule__Server__NameAssignment_2");
			builder.put(grammarAccess.getServerAccess().getConnectionURLAssignment_4_1(), "rule__Server__ConnectionURLAssignment_4_1");
			builder.put(grammarAccess.getServerAccess().getConnectionOptionsAssignment_5_1(), "rule__Server__ConnectionOptionsAssignment_5_1");
			builder.put(grammarAccess.getEPackageAccess().getNameAssignment_2(), "rule__EPackage__NameAssignment_2");
			builder.put(grammarAccess.getEPackageAccess().getNsURIAssignment_4_1(), "rule__EPackage__NsURIAssignment_4_1");
			builder.put(grammarAccess.getEPackageAccess().getNsPrefixAssignment_5_1(), "rule__EPackage__NsPrefixAssignment_5_1");
			builder.put(grammarAccess.getEPackageAccess().getEAnnotationsAssignment_6_2(), "rule__EPackage__EAnnotationsAssignment_6_2");
			builder.put(grammarAccess.getEPackageAccess().getEAnnotationsAssignment_6_3_1(), "rule__EPackage__EAnnotationsAssignment_6_3_1");
			builder.put(grammarAccess.getEPackageAccess().getEClassifiersAssignment_7_2(), "rule__EPackage__EClassifiersAssignment_7_2");
			builder.put(grammarAccess.getEPackageAccess().getEClassifiersAssignment_7_3_1(), "rule__EPackage__EClassifiersAssignment_7_3_1");
			builder.put(grammarAccess.getEPackageAccess().getESubpackagesAssignment_8_2(), "rule__EPackage__ESubpackagesAssignment_8_2");
			builder.put(grammarAccess.getEPackageAccess().getESubpackagesAssignment_8_3_1(), "rule__EPackage__ESubpackagesAssignment_8_3_1");
			builder.put(grammarAccess.getMoSystemAccess().getEClassAssignment_3_1(), "rule__MoSystem__EClassAssignment_3_1");
			builder.put(grammarAccess.getMoSystemAccess().getAgentsAssignment_4_2(), "rule__MoSystem__AgentsAssignment_4_2");
			builder.put(grammarAccess.getMoSystemAccess().getAgentsAssignment_4_3_1(), "rule__MoSystem__AgentsAssignment_4_3_1");
			builder.put(grammarAccess.getConnectionOptionsAccess().getAutomaticReconnectAssignment_3_1(), "rule__ConnectionOptions__AutomaticReconnectAssignment_3_1");
			builder.put(grammarAccess.getConnectionOptionsAccess().getCleanSessionAssignment_4_1(), "rule__ConnectionOptions__CleanSessionAssignment_4_1");
			builder.put(grammarAccess.getConnectionOptionsAccess().getConnectionTimeOutAssignment_5_1(), "rule__ConnectionOptions__ConnectionTimeOutAssignment_5_1");
			builder.put(grammarAccess.getConnectionOptionsAccess().getSetMaxInflightAssignment_6_1(), "rule__ConnectionOptions__SetMaxInflightAssignment_6_1");
			builder.put(grammarAccess.getEAnnotationAccess().getSourceAssignment_3_1(), "rule__EAnnotation__SourceAssignment_3_1");
			builder.put(grammarAccess.getEAnnotationAccess().getReferencesAssignment_4_2(), "rule__EAnnotation__ReferencesAssignment_4_2");
			builder.put(grammarAccess.getEAnnotationAccess().getReferencesAssignment_4_3_1(), "rule__EAnnotation__ReferencesAssignment_4_3_1");
			builder.put(grammarAccess.getEAnnotationAccess().getEAnnotationsAssignment_5_2(), "rule__EAnnotation__EAnnotationsAssignment_5_2");
			builder.put(grammarAccess.getEAnnotationAccess().getEAnnotationsAssignment_5_3_1(), "rule__EAnnotation__EAnnotationsAssignment_5_3_1");
			builder.put(grammarAccess.getEAnnotationAccess().getDetailsAssignment_6_2(), "rule__EAnnotation__DetailsAssignment_6_2");
			builder.put(grammarAccess.getEAnnotationAccess().getDetailsAssignment_6_3_1(), "rule__EAnnotation__DetailsAssignment_6_3_1");
			builder.put(grammarAccess.getEAnnotationAccess().getContentsAssignment_7_2(), "rule__EAnnotation__ContentsAssignment_7_2");
			builder.put(grammarAccess.getEAnnotationAccess().getContentsAssignment_7_3_1(), "rule__EAnnotation__ContentsAssignment_7_3_1");
			builder.put(grammarAccess.getEStringToStringMapEntryAccess().getKeyAssignment_3_1(), "rule__EStringToStringMapEntry__KeyAssignment_3_1");
			builder.put(grammarAccess.getEStringToStringMapEntryAccess().getValueAssignment_4_1(), "rule__EStringToStringMapEntry__ValueAssignment_4_1");
			builder.put(grammarAccess.getETypeParameterAccess().getNameAssignment_2(), "rule__ETypeParameter__NameAssignment_2");
			builder.put(grammarAccess.getETypeParameterAccess().getEAnnotationsAssignment_4_2(), "rule__ETypeParameter__EAnnotationsAssignment_4_2");
			builder.put(grammarAccess.getETypeParameterAccess().getEAnnotationsAssignment_4_3_1(), "rule__ETypeParameter__EAnnotationsAssignment_4_3_1");
			builder.put(grammarAccess.getETypeParameterAccess().getEBoundsAssignment_5_2(), "rule__ETypeParameter__EBoundsAssignment_5_2");
			builder.put(grammarAccess.getETypeParameterAccess().getEBoundsAssignment_5_3_1(), "rule__ETypeParameter__EBoundsAssignment_5_3_1");
			builder.put(grammarAccess.getEClassAccess().getAbstractAssignment_1(), "rule__EClass__AbstractAssignment_1");
			builder.put(grammarAccess.getEClassAccess().getInterfaceAssignment_2(), "rule__EClass__InterfaceAssignment_2");
			builder.put(grammarAccess.getEClassAccess().getNameAssignment_4(), "rule__EClass__NameAssignment_4");
			builder.put(grammarAccess.getEClassAccess().getInstanceClassNameAssignment_6_1(), "rule__EClass__InstanceClassNameAssignment_6_1");
			builder.put(grammarAccess.getEClassAccess().getInstanceTypeNameAssignment_7_1(), "rule__EClass__InstanceTypeNameAssignment_7_1");
			builder.put(grammarAccess.getEClassAccess().getESuperTypesAssignment_8_2(), "rule__EClass__ESuperTypesAssignment_8_2");
			builder.put(grammarAccess.getEClassAccess().getESuperTypesAssignment_8_3_1(), "rule__EClass__ESuperTypesAssignment_8_3_1");
			builder.put(grammarAccess.getEClassAccess().getEAnnotationsAssignment_9_2(), "rule__EClass__EAnnotationsAssignment_9_2");
			builder.put(grammarAccess.getEClassAccess().getEAnnotationsAssignment_9_3_1(), "rule__EClass__EAnnotationsAssignment_9_3_1");
			builder.put(grammarAccess.getEClassAccess().getETypeParametersAssignment_10_2(), "rule__EClass__ETypeParametersAssignment_10_2");
			builder.put(grammarAccess.getEClassAccess().getETypeParametersAssignment_10_3_1(), "rule__EClass__ETypeParametersAssignment_10_3_1");
			builder.put(grammarAccess.getEClassAccess().getEOperationsAssignment_11_2(), "rule__EClass__EOperationsAssignment_11_2");
			builder.put(grammarAccess.getEClassAccess().getEOperationsAssignment_11_3_1(), "rule__EClass__EOperationsAssignment_11_3_1");
			builder.put(grammarAccess.getEClassAccess().getEStructuralFeaturesAssignment_12_2(), "rule__EClass__EStructuralFeaturesAssignment_12_2");
			builder.put(grammarAccess.getEClassAccess().getEStructuralFeaturesAssignment_12_3_1(), "rule__EClass__EStructuralFeaturesAssignment_12_3_1");
			builder.put(grammarAccess.getEClassAccess().getEGenericSuperTypesAssignment_13_2(), "rule__EClass__EGenericSuperTypesAssignment_13_2");
			builder.put(grammarAccess.getEClassAccess().getEGenericSuperTypesAssignment_13_3_1(), "rule__EClass__EGenericSuperTypesAssignment_13_3_1");
			builder.put(grammarAccess.getEDataType_ImplAccess().getNameAssignment_2(), "rule__EDataType_Impl__NameAssignment_2");
			builder.put(grammarAccess.getEDataType_ImplAccess().getInstanceClassNameAssignment_4_1(), "rule__EDataType_Impl__InstanceClassNameAssignment_4_1");
			builder.put(grammarAccess.getEDataType_ImplAccess().getInstanceTypeNameAssignment_5_1(), "rule__EDataType_Impl__InstanceTypeNameAssignment_5_1");
			builder.put(grammarAccess.getEDataType_ImplAccess().getSerializableAssignment_6_1(), "rule__EDataType_Impl__SerializableAssignment_6_1");
			builder.put(grammarAccess.getEDataType_ImplAccess().getEAnnotationsAssignment_7_2(), "rule__EDataType_Impl__EAnnotationsAssignment_7_2");
			builder.put(grammarAccess.getEDataType_ImplAccess().getEAnnotationsAssignment_7_3_1(), "rule__EDataType_Impl__EAnnotationsAssignment_7_3_1");
			builder.put(grammarAccess.getEDataType_ImplAccess().getETypeParametersAssignment_8_2(), "rule__EDataType_Impl__ETypeParametersAssignment_8_2");
			builder.put(grammarAccess.getEDataType_ImplAccess().getETypeParametersAssignment_8_3_1(), "rule__EDataType_Impl__ETypeParametersAssignment_8_3_1");
			builder.put(grammarAccess.getEEnumAccess().getNameAssignment_2(), "rule__EEnum__NameAssignment_2");
			builder.put(grammarAccess.getEEnumAccess().getInstanceClassNameAssignment_4_1(), "rule__EEnum__InstanceClassNameAssignment_4_1");
			builder.put(grammarAccess.getEEnumAccess().getInstanceTypeNameAssignment_5_1(), "rule__EEnum__InstanceTypeNameAssignment_5_1");
			builder.put(grammarAccess.getEEnumAccess().getSerializableAssignment_6_1(), "rule__EEnum__SerializableAssignment_6_1");
			builder.put(grammarAccess.getEEnumAccess().getEAnnotationsAssignment_7_2(), "rule__EEnum__EAnnotationsAssignment_7_2");
			builder.put(grammarAccess.getEEnumAccess().getEAnnotationsAssignment_7_3_1(), "rule__EEnum__EAnnotationsAssignment_7_3_1");
			builder.put(grammarAccess.getEEnumAccess().getETypeParametersAssignment_8_2(), "rule__EEnum__ETypeParametersAssignment_8_2");
			builder.put(grammarAccess.getEEnumAccess().getETypeParametersAssignment_8_3_1(), "rule__EEnum__ETypeParametersAssignment_8_3_1");
			builder.put(grammarAccess.getEEnumAccess().getELiteralsAssignment_9_2(), "rule__EEnum__ELiteralsAssignment_9_2");
			builder.put(grammarAccess.getEEnumAccess().getELiteralsAssignment_9_3_1(), "rule__EEnum__ELiteralsAssignment_9_3_1");
			builder.put(grammarAccess.getEGenericTypeAccess().getETypeParameterAssignment_3_1(), "rule__EGenericType__ETypeParameterAssignment_3_1");
			builder.put(grammarAccess.getEGenericTypeAccess().getEClassifierAssignment_4_1(), "rule__EGenericType__EClassifierAssignment_4_1");
			builder.put(grammarAccess.getEGenericTypeAccess().getEUpperBoundAssignment_5_1(), "rule__EGenericType__EUpperBoundAssignment_5_1");
			builder.put(grammarAccess.getEGenericTypeAccess().getETypeArgumentsAssignment_6_2(), "rule__EGenericType__ETypeArgumentsAssignment_6_2");
			builder.put(grammarAccess.getEGenericTypeAccess().getETypeArgumentsAssignment_6_3_1(), "rule__EGenericType__ETypeArgumentsAssignment_6_3_1");
			builder.put(grammarAccess.getEGenericTypeAccess().getELowerBoundAssignment_7_1(), "rule__EGenericType__ELowerBoundAssignment_7_1");
			builder.put(grammarAccess.getEOperationAccess().getNameAssignment_2(), "rule__EOperation__NameAssignment_2");
			builder.put(grammarAccess.getEOperationAccess().getOrderedAssignment_4_1(), "rule__EOperation__OrderedAssignment_4_1");
			builder.put(grammarAccess.getEOperationAccess().getUniqueAssignment_5_1(), "rule__EOperation__UniqueAssignment_5_1");
			builder.put(grammarAccess.getEOperationAccess().getLowerBoundAssignment_6_1(), "rule__EOperation__LowerBoundAssignment_6_1");
			builder.put(grammarAccess.getEOperationAccess().getUpperBoundAssignment_7_1(), "rule__EOperation__UpperBoundAssignment_7_1");
			builder.put(grammarAccess.getEOperationAccess().getETypeAssignment_8_1(), "rule__EOperation__ETypeAssignment_8_1");
			builder.put(grammarAccess.getEOperationAccess().getEExceptionsAssignment_9_2(), "rule__EOperation__EExceptionsAssignment_9_2");
			builder.put(grammarAccess.getEOperationAccess().getEExceptionsAssignment_9_3_1(), "rule__EOperation__EExceptionsAssignment_9_3_1");
			builder.put(grammarAccess.getEOperationAccess().getEAnnotationsAssignment_10_2(), "rule__EOperation__EAnnotationsAssignment_10_2");
			builder.put(grammarAccess.getEOperationAccess().getEAnnotationsAssignment_10_3_1(), "rule__EOperation__EAnnotationsAssignment_10_3_1");
			builder.put(grammarAccess.getEOperationAccess().getEGenericTypeAssignment_11_1(), "rule__EOperation__EGenericTypeAssignment_11_1");
			builder.put(grammarAccess.getEOperationAccess().getETypeParametersAssignment_12_2(), "rule__EOperation__ETypeParametersAssignment_12_2");
			builder.put(grammarAccess.getEOperationAccess().getETypeParametersAssignment_12_3_1(), "rule__EOperation__ETypeParametersAssignment_12_3_1");
			builder.put(grammarAccess.getEOperationAccess().getEParametersAssignment_13_2(), "rule__EOperation__EParametersAssignment_13_2");
			builder.put(grammarAccess.getEOperationAccess().getEParametersAssignment_13_3_1(), "rule__EOperation__EParametersAssignment_13_3_1");
			builder.put(grammarAccess.getEOperationAccess().getEGenericExceptionsAssignment_14_2(), "rule__EOperation__EGenericExceptionsAssignment_14_2");
			builder.put(grammarAccess.getEOperationAccess().getEGenericExceptionsAssignment_14_3_1(), "rule__EOperation__EGenericExceptionsAssignment_14_3_1");
			builder.put(grammarAccess.getEParameterAccess().getNameAssignment_2(), "rule__EParameter__NameAssignment_2");
			builder.put(grammarAccess.getEParameterAccess().getOrderedAssignment_4_1(), "rule__EParameter__OrderedAssignment_4_1");
			builder.put(grammarAccess.getEParameterAccess().getUniqueAssignment_5_1(), "rule__EParameter__UniqueAssignment_5_1");
			builder.put(grammarAccess.getEParameterAccess().getLowerBoundAssignment_6_1(), "rule__EParameter__LowerBoundAssignment_6_1");
			builder.put(grammarAccess.getEParameterAccess().getUpperBoundAssignment_7_1(), "rule__EParameter__UpperBoundAssignment_7_1");
			builder.put(grammarAccess.getEParameterAccess().getETypeAssignment_8_1(), "rule__EParameter__ETypeAssignment_8_1");
			builder.put(grammarAccess.getEParameterAccess().getEAnnotationsAssignment_9_2(), "rule__EParameter__EAnnotationsAssignment_9_2");
			builder.put(grammarAccess.getEParameterAccess().getEAnnotationsAssignment_9_3_1(), "rule__EParameter__EAnnotationsAssignment_9_3_1");
			builder.put(grammarAccess.getEParameterAccess().getEGenericTypeAssignment_10_1(), "rule__EParameter__EGenericTypeAssignment_10_1");
			builder.put(grammarAccess.getEAttributeAccess().getVolatileAssignment_1(), "rule__EAttribute__VolatileAssignment_1");
			builder.put(grammarAccess.getEAttributeAccess().getTransientAssignment_2(), "rule__EAttribute__TransientAssignment_2");
			builder.put(grammarAccess.getEAttributeAccess().getUnsettableAssignment_3(), "rule__EAttribute__UnsettableAssignment_3");
			builder.put(grammarAccess.getEAttributeAccess().getDerivedAssignment_4(), "rule__EAttribute__DerivedAssignment_4");
			builder.put(grammarAccess.getEAttributeAccess().getIDAssignment_5(), "rule__EAttribute__IDAssignment_5");
			builder.put(grammarAccess.getEAttributeAccess().getNameAssignment_7(), "rule__EAttribute__NameAssignment_7");
			builder.put(grammarAccess.getEAttributeAccess().getOrderedAssignment_9_1(), "rule__EAttribute__OrderedAssignment_9_1");
			builder.put(grammarAccess.getEAttributeAccess().getUniqueAssignment_10_1(), "rule__EAttribute__UniqueAssignment_10_1");
			builder.put(grammarAccess.getEAttributeAccess().getLowerBoundAssignment_11_1(), "rule__EAttribute__LowerBoundAssignment_11_1");
			builder.put(grammarAccess.getEAttributeAccess().getUpperBoundAssignment_12_1(), "rule__EAttribute__UpperBoundAssignment_12_1");
			builder.put(grammarAccess.getEAttributeAccess().getChangeableAssignment_13_1(), "rule__EAttribute__ChangeableAssignment_13_1");
			builder.put(grammarAccess.getEAttributeAccess().getDefaultValueLiteralAssignment_14_1(), "rule__EAttribute__DefaultValueLiteralAssignment_14_1");
			builder.put(grammarAccess.getEAttributeAccess().getETypeAssignment_15_1(), "rule__EAttribute__ETypeAssignment_15_1");
			builder.put(grammarAccess.getEAttributeAccess().getEAnnotationsAssignment_16_2(), "rule__EAttribute__EAnnotationsAssignment_16_2");
			builder.put(grammarAccess.getEAttributeAccess().getEAnnotationsAssignment_16_3_1(), "rule__EAttribute__EAnnotationsAssignment_16_3_1");
			builder.put(grammarAccess.getEAttributeAccess().getEGenericTypeAssignment_17_1(), "rule__EAttribute__EGenericTypeAssignment_17_1");
			builder.put(grammarAccess.getEReferenceAccess().getVolatileAssignment_1(), "rule__EReference__VolatileAssignment_1");
			builder.put(grammarAccess.getEReferenceAccess().getTransientAssignment_2(), "rule__EReference__TransientAssignment_2");
			builder.put(grammarAccess.getEReferenceAccess().getUnsettableAssignment_3(), "rule__EReference__UnsettableAssignment_3");
			builder.put(grammarAccess.getEReferenceAccess().getDerivedAssignment_4(), "rule__EReference__DerivedAssignment_4");
			builder.put(grammarAccess.getEReferenceAccess().getContainmentAssignment_5(), "rule__EReference__ContainmentAssignment_5");
			builder.put(grammarAccess.getEReferenceAccess().getNameAssignment_7(), "rule__EReference__NameAssignment_7");
			builder.put(grammarAccess.getEReferenceAccess().getOrderedAssignment_9_1(), "rule__EReference__OrderedAssignment_9_1");
			builder.put(grammarAccess.getEReferenceAccess().getUniqueAssignment_10_1(), "rule__EReference__UniqueAssignment_10_1");
			builder.put(grammarAccess.getEReferenceAccess().getLowerBoundAssignment_11_1(), "rule__EReference__LowerBoundAssignment_11_1");
			builder.put(grammarAccess.getEReferenceAccess().getUpperBoundAssignment_12_1(), "rule__EReference__UpperBoundAssignment_12_1");
			builder.put(grammarAccess.getEReferenceAccess().getChangeableAssignment_13_1(), "rule__EReference__ChangeableAssignment_13_1");
			builder.put(grammarAccess.getEReferenceAccess().getDefaultValueLiteralAssignment_14_1(), "rule__EReference__DefaultValueLiteralAssignment_14_1");
			builder.put(grammarAccess.getEReferenceAccess().getResolveProxiesAssignment_15_1(), "rule__EReference__ResolveProxiesAssignment_15_1");
			builder.put(grammarAccess.getEReferenceAccess().getETypeAssignment_16_1(), "rule__EReference__ETypeAssignment_16_1");
			builder.put(grammarAccess.getEReferenceAccess().getEOppositeAssignment_17_1(), "rule__EReference__EOppositeAssignment_17_1");
			builder.put(grammarAccess.getEReferenceAccess().getEKeysAssignment_18_2(), "rule__EReference__EKeysAssignment_18_2");
			builder.put(grammarAccess.getEReferenceAccess().getEKeysAssignment_18_3_1(), "rule__EReference__EKeysAssignment_18_3_1");
			builder.put(grammarAccess.getEReferenceAccess().getEAnnotationsAssignment_19_2(), "rule__EReference__EAnnotationsAssignment_19_2");
			builder.put(grammarAccess.getEReferenceAccess().getEAnnotationsAssignment_19_3_1(), "rule__EReference__EAnnotationsAssignment_19_3_1");
			builder.put(grammarAccess.getEReferenceAccess().getEGenericTypeAssignment_20_1(), "rule__EReference__EGenericTypeAssignment_20_1");
			builder.put(grammarAccess.getEEnumLiteralAccess().getNameAssignment_2(), "rule__EEnumLiteral__NameAssignment_2");
			builder.put(grammarAccess.getEEnumLiteralAccess().getValueAssignment_4_1(), "rule__EEnumLiteral__ValueAssignment_4_1");
			builder.put(grammarAccess.getEEnumLiteralAccess().getLiteralAssignment_5_1(), "rule__EEnumLiteral__LiteralAssignment_5_1");
			builder.put(grammarAccess.getEEnumLiteralAccess().getEAnnotationsAssignment_6_2(), "rule__EEnumLiteral__EAnnotationsAssignment_6_2");
			builder.put(grammarAccess.getEEnumLiteralAccess().getEAnnotationsAssignment_6_3_1(), "rule__EEnumLiteral__EAnnotationsAssignment_6_3_1");
			builder.put(grammarAccess.getMOAgentAccess().getNameAssignment_2(), "rule__MOAgent__NameAssignment_2");
			builder.put(grammarAccess.getMOAgentAccess().getTopicAssignment_4_1(), "rule__MOAgent__TopicAssignment_4_1");
			builder.put(grammarAccess.getMOAgentAccess().getSyncAssignment_5_1(), "rule__MOAgent__SyncAssignment_5_1");
			builder.put(grammarAccess.getMOAgentAccess().getEClassAssignment_6_1(), "rule__MOAgent__EClassAssignment_6_1");
			builder.put(grammarAccess.getMOAgentAccess().getServerAssignment_7_1(), "rule__MOAgent__ServerAssignment_7_1");
			builder.put(grammarAccess.getMOAgentAccess().getElementsAssignment_8_2(), "rule__MOAgent__ElementsAssignment_8_2");
			builder.put(grammarAccess.getMOAgentAccess().getElementsAssignment_8_3_1(), "rule__MOAgent__ElementsAssignment_8_3_1");
			builder.put(grammarAccess.getMOAgentAccess().getDerivedpropertiesAssignment_9_2(), "rule__MOAgent__DerivedpropertiesAssignment_9_2");
			builder.put(grammarAccess.getMOAgentAccess().getDerivedpropertiesAssignment_9_3_1(), "rule__MOAgent__DerivedpropertiesAssignment_9_3_1");
			builder.put(grammarAccess.getDerivedPropertyAccess().getNameAssignment_2(), "rule__DerivedProperty__NameAssignment_2");
			builder.put(grammarAccess.getDerivedPropertyAccess().getTopicAssignment_4_1(), "rule__DerivedProperty__TopicAssignment_4_1");
			builder.put(grammarAccess.getDerivedPropertyAccess().getSyncAssignment_5_1(), "rule__DerivedProperty__SyncAssignment_5_1");
			builder.put(grammarAccess.getDerivedPropertyAccess().getEClassAssignment_6_1(), "rule__DerivedProperty__EClassAssignment_6_1");
			builder.put(grammarAccess.getMOPropertyAccess().getNameAssignment_2(), "rule__MOProperty__NameAssignment_2");
			builder.put(grammarAccess.getMOPropertyAccess().getTopicAssignment_4_1(), "rule__MOProperty__TopicAssignment_4_1");
			builder.put(grammarAccess.getMOPropertyAccess().getSyncAssignment_5_1(), "rule__MOProperty__SyncAssignment_5_1");
			builder.put(grammarAccess.getMOPropertyAccess().getEClassAssignment_6_1(), "rule__MOProperty__EClassAssignment_6_1");
			builder.put(grammarAccess.getMOPropertyAccess().getPropertiesAssignment_7_2(), "rule__MOProperty__PropertiesAssignment_7_2");
			builder.put(grammarAccess.getMOPropertyAccess().getPropertiesAssignment_7_3_1(), "rule__MOProperty__PropertiesAssignment_7_3_1");
			builder.put(grammarAccess.getMOValueAccess().getNameAssignment_2(), "rule__MOValue__NameAssignment_2");
			builder.put(grammarAccess.getMOValueAccess().getTopicAssignment_4_1(), "rule__MOValue__TopicAssignment_4_1");
			builder.put(grammarAccess.getMOValueAccess().getSyncAssignment_5_1(), "rule__MOValue__SyncAssignment_5_1");
			builder.put(grammarAccess.getMOValueAccess().getEAttributeAssignment_6_1(), "rule__MOValue__EAttributeAssignment_6_1");
			builder.put(grammarAccess.getMOValueAccess().getPropertiesAssignment_7_2(), "rule__MOValue__PropertiesAssignment_7_2");
			builder.put(grammarAccess.getMOValueAccess().getPropertiesAssignment_7_3_1(), "rule__MOValue__PropertiesAssignment_7_3_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private MosumoGrammarAccess grammarAccess;

	@Override
	protected InternalMosumoParser createParser() {
		InternalMosumoParser result = new InternalMosumoParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public MosumoGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MosumoGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
