/*
 * generated by Xtext 2.23.0
 */
package at.jku.mosumo.lang.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMosumoScopeProvider extends DelegatingScopeProvider {
}
